# Generated by Django 3.0.9 on 2022-06-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_remove_userregistrationmodel_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationmodel',
            name='angelonestatus',
            field=models.IntegerField(default=0),
        ),
    ]
