# Generated by Django 3.0.9 on 2022-06-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_userregistrationmodel_angelemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
