# Generated by Django 3.0.9 on 2022-07-05 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0008_auto_20220624_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('ttype', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('profit', models.CharField(max_length=50)),
                ('sl', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('name_ltp', models.CharField(max_length=50)),
                ('symbol_ltp', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
