# Generated by Django 3.0.9 on 2022-07-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('expiry', models.CharField(max_length=50)),
                ('strike', models.CharField(max_length=50)),
                ('lotsize', models.CharField(max_length=50)),
                ('instrumenttype', models.CharField(max_length=50)),
                ('exch_seg', models.CharField(max_length=50)),
                ('tick_size', models.CharField(max_length=50)),
            ],
        ),
    ]
