# Generated by Django 3.0.9 on 2022-07-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_order_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exc',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
