# Generated by Django 3.0.9 on 2022-07-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_auto_20220711_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='limitvalue',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
