# Generated by Django 3.0.9 on 2022-07-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_order_limitvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationmodel',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
